Refactor Library
cboard-org/cboard-ai-engine pull request #1
Opened 2024-02-23 19:56 UTC by RodriSanchez1

2024-02-27 15:51 UTC, maxicapodacqua requested changes

2024-02-27 15:51 UTC, maxicapodacqua commented on src/engine.ts
> +      axios.get(globalSymbolsURL, {
Maybe in a future iteration use `fetch` instead of `axios` as now it's included in v8 and node

2024-02-27 15:51 UTC, maxicapodacqua commented on src/engine.ts
> +let pictonizerURL = "";
Consider using a global config object instead of multiple global variables

2024-02-27 15:51 UTC, maxicapodacqua commented on src/engine.ts
> +let globalSymbolsURL = "https://www.globalsymbols.com/api/v1/labels/search/";
Use a `const` for this default value

2024-02-27 15:51 UTC, maxicapodacqua commented on src/engine.ts
> +  //https://learnprompting.org/es/docs/intro Imageprompting
Add a tech debt issue for this

2024-02-27 15:51 UTC, maxicapodacqua commented on src/engine.ts
> +    });
Move this to the catch block, `finally` should be used to release resources

2024-02-27 15:51 UTC, maxicapodacqua commented on src/engine.ts
> +          id: 123456, //TODO add library to get id nanoid
Add tech debt issue for this

2024-02-27 15:51 UTC, maxicapodacqua commented on src/request.ts
Maybe rename this file? I'm not sure what are these constants used for. If the file is only for declaring constants use `constants.ts`

2024-02-27 16:23 UTC, shayc commented on src/engine.ts
> +let openaiInstance: OpenAIApi;
`openAIInstance`, for consistency across other variables in this file where open AI is used.

2024-02-27 16:39 UTC, shayc commented on src/engine.ts
> +  } catch (error: Error | any) {
Is `any` needed here?

2024-02-27 23:12 UTC, RodriSanchez1 commented on src/request.ts
Done

2024-02-28 01:25 UTC, RodriSanchez1 commented on src/engine.ts
> +  } catch (error: Error | any) {
I get `Catch clause variable type annotation must be 'any' or 'unknown' if specified.` if delet it. Which one is fits better in this case? `any` or `unknow`

2024-02-28 19:25 UTC, RodriSanchez1 commented on src/engine.ts
> +      picto: data.map((picto: any) => picto.picto.image_url),
How can i deal with this, if the data is a third party API response? I will create an issue of this

2024-02-28 19:29 UTC, RodriSanchez1 commented on src/engine.ts
> +  //https://learnprompting.org/es/docs/intro Imageprompting
@hectoritr Can you create this issue?

2024-02-28 21:05 UTC, RodriSanchez1 commented on src/engine.ts
> +          id: 123456, //TODO add library to get id nanoid
Done #4

2024-02-28 21:07 UTC, RodriSanchez1 commented on src/engine.ts
> +  locale: string;
I will do it in other PR #5

2024-02-28 21:19 UTC, merged